# Question 1
You are required to make a user-agent that will crawl the WWW (your familiar domain)
to produce dataset of a particular website.
 the web site can be as simple as a list of webpages and what other pages they
link to
 the output does not need to be in XHTML (or HTML) form
a multi-stage approach (e.g. produce the xhtml or html in csv format )

In [ ]:
#import Required Libraries
import pandas as pd
from pandas import DataFrame
import numpy as np
import time
from urllib.request import Request, urlopen
from urllib.error import  URLError

In [ ]:
start_time = time.time()

req = Request('https://www.lendingclub.com/')
try:
    response = urlopen(req)
except URLError as e:
    if hasattr(e, 'reason'):
        print('We failed to reach a server.')
        print('Reason: ', e.reason)
    elif hasattr(e, 'code'):
        print('The server couldn\'t fulfill the request.')
        print('Error code: ', e.code)
else:
        print("Everything is fine")
        
q1 = pd.read_csv('https://lending-club.s3.amazonaws.com/LoanStats_2019Q1.csv')
q2 = pd.read_csv('https://lending-club.s3.amazonaws.com/LoanStats_2019Q2.csv')
q3 = pd.read_csv('https://lending-club.s3.amazonaws.com/LoanStats_2019Q3.csv')
q4 = pd.read_csv('https://lending-club.s3.amazonaws.com/LoanStats_2019Q4.csv')

time.sleep(1)

print('*** Process Completeed ***')
print('Time used:\t',time.time()-start_time)

Everything is fine

D:\Anaconda3\envs\scraper\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
D:\Anaconda3\envs\scraper\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (0,144,145,146) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

*** Process Completeed ***
Time used:	 257.5178220272064

In [ ]:
#Merging all sub DataFrame to single DataFrame
loans = pd.concat([q1,q2,q3,q4]) 
loans

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,149203043,NaN,24000.0,24000.0,24000.0,60 months,13.90%,557.20,C,C1,...,473.24,20656.42,557.2,N,NaN,NaN,NaN,NaN,NaN,NaN
1,149354242,NaN,18500.0,18500.0,18500.0,60 months,14.74%,437.60,C,C2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,149355875,NaN,24000.0,24000.0,24000.0,36 months,8.19%,754.18,A,A4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,149437986,NaN,2800.0,2800.0,2775.0,36 months,8.19%,87.99,A,A4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,149511512,NaN,8800.0,8800.0,8800.0,36 months,20.00%,327.04,D,D2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128257,158206429,NaN,14875.0,14875.0,14875.0,36 months,16.95%,529.97,C,C4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128260,Total amount funded in policy code 1: 2087537550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128261,Total amount funded in policy code 2: 988164725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Contains info about col and datatype
loans.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518123 entries, 0 to 128261
Data columns (total 150 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   id                                          518115 non-null  object
 1   member_id                                   0 non-null       float64
 2   loan_amnt                                   518107 non-null  float64
 3   funded_amnt                                 518107 non-null  float64
 4   funded_amnt_inv                             518107 non-null  float64
 5   term                                        518107 non-null  object
 6   int_rate                                    518107 non-null  object
 7   installment                                 518107 non-null  float64
 8   grade                                       518107 non-null  object
 9   sub_grade                                   518107 non-null  object
 10  emp_title                                   440579 non-null  object
 11  emp_length                                  471856 non-null  object
 12  home_ownership                              518107 non-null  object
 13  annual_inc                                  518107 non-null  float64
 14  verification_status                         518107 non-null  object
 15  issue_d                                     518107 non-null  object
 16  loan_status                                 518107 non-null  object
 17  pymnt_plan                                  518107 non-null  object
 18  url                                         518107 non-null  object
 19  desc                                        0 non-null       float64
 20  purpose                                     518107 non-null  object
 21  title                                       518107 non-null  object
 22  zip_code                                    518107 non-null  object
 23  addr_state                                  518107 non-null  object
 24  dti                                         516962 non-null  float64
 25  delinq_2yrs                                 518107 non-null  float64
 26  earliest_cr_line                            518107 non-null  object
 27  fico_range_low                              518107 non-null  float64
 28  fico_range_high                             518107 non-null  float64
 29  inq_last_6mths                              518107 non-null  float64
 30  mths_since_last_delinq                      225554 non-null  float64
 31  mths_since_last_record                      55121 non-null   float64
 32  open_acc                                    518107 non-null  float64
 33  pub_rec                                     518107 non-null  float64
 34  revol_bal                                   518107 non-null  float64
 35  revol_util                                  517433 non-null  object
 36  total_acc                                   518107 non-null  float64
 37  initial_list_status                         518107 non-null  object
 38  out_prncp                                   518107 non-null  float64
 39  out_prncp_inv                               518107 non-null  float64
 40  total_pymnt                                 518107 non-null  float64
 41  total_pymnt_inv                             518107 non-null  float64
 42  total_rec_prncp                             518107 non-null  float64
 43  total_rec_int                               518107 non-null  float64
 44  total_rec_late_fee                          518107 non-null  float64
 45  recoveries                                  518107 non-null  float64
 46  collection_recovery_fee                     518107 non-null  float64
 47  last_pymnt_d                                517244 non-null  object
 48  last_pymnt_amnt                             518107 non-null  float64
 49  next_pymnt_d                                442780 non-null  object
 50  last_credit_pull_d                          518104 non-null  object
 51  last_fico_range_high                        518107 non-null  float64
 52  last_fico_range_low                         518107 non-null  float64
 53  collections_12_mths_ex_med                  518107 non-null  float64
 54  mths_since_last_major_derog                 112856 non-null  float64
 55  policy_code                                 518107 non-null  float64
 56  application_type                            518107 non-null  object
 57  annual_inc_joint                            71894 non-null   float64
 58  dti_joint                                   71894 non-null   float64
 59  verification_status_joint                   63354 non-null   object
 60  acc_now_delinq                              518107 non-null  float64
 61  tot_coll_amt                                518107 non-null  float64
 62  tot_cur_bal                                 518107 non-null  float64
 63  open_acc_6m                                 518107 non-null  float64
 64  open_act_il                                 518107 non-null  float64
 65  open_il_12m                                 518107 non-null  float64
 66  open_il_24m                                 518107 non-null  float64
 67  mths_since_rcnt_il                          504008 non-null  float64
 68  total_bal_il                                518107 non-null  float64
 69  il_util                                     445800 non-null  float64
 70  open_rv_12m                                 518107 non-null  float64
 71  open_rv_24m                                 518107 non-null  float64
 72  max_bal_bc                                  518107 non-null  float64
 73  all_util                                    517990 non-null  float64
 74  total_rev_hi_lim                            518107 non-null  float64
 75  inq_fi                                      518107 non-null  float64
 76  total_cu_tl                                 518107 non-null  float64
 77  inq_last_12m                                518107 non-null  float64
 78  acc_open_past_24mths                        518107 non-null  float64
 79  avg_cur_bal                                 518075 non-null  float64
 80  bc_open_to_buy                              511838 non-null  float64
 81  bc_util                                     511580 non-null  float64
 82  chargeoff_within_12_mths                    518107 non-null  float64
 83  delinq_amnt                                 518107 non-null  float64
 84  mo_sin_old_il_acct                          504008 non-null  float64
 85  mo_sin_old_rev_tl_op                        518107 non-null  float64
 86  mo_sin_rcnt_rev_tl_op                       518107 non-null  float64
 87  mo_sin_rcnt_tl                              518107 non-null  float64
 88  mort_acc                                    518107 non-null  float64
 89  mths_since_recent_bc                        512186 non-null  float64
 90  mths_since_recent_bc_dlq                    102558 non-null  float64
 91  mths_since_recent_inq                       455886 non-null  float64
 92  mths_since_recent_revol_delinq              149481 non-null  float64
 93  num_accts_ever_120_pd                       518107 non-null  float64
 94  num_actv_bc_tl                              518107 non-null  float64
 95  num_actv_rev_tl                             518107 non-null  float64
 96  num_bc_sats                                 518107 non-null  float64
 97  num_bc_tl                                   518107 non-null  float64
 98  num_il_tl                                   518107 non-null  float64
 99  num_op_rev_tl                               518107 non-null  float64
 100 num_rev_accts                               518107 non-null  float64
 101 num_rev_tl_bal_gt_0                         518107 non-null  float64
 102 num_sats                                    518107 non-null  float64
 103 num_tl_120dpd_2m                            511001 non-null  float64
 104 num_tl_30dpd                                518107 non-null  float64
 105 num_tl_90g_dpd_24m                          518107 non-null  float64
 106 num_tl_op_past_12m                          518107 non-null  float64
 107 pct_tl_nvr_dlq                              518107 non-null  float64
 108 percent_bc_gt_75                            511803 non-null  float64
 109 pub_rec_bankruptcies                        518107 non-null  float64
 110 tax_liens                                   518107 non-null  float64
 111 tot_hi_cred_lim                             518107 non-null  float64
 112 total_bal_ex_mort                           518107 non-null  float64
 113 total_bc_limit                              518107 non-null  float64
 114 total_il_high_credit_limit                  518107 non-null  float64
 115 revol_bal_joint                             71894 non-null   float64
 116 sec_app_fico_range_low                      71894 non-null   float64
 117 sec_app_fico_range_high                     71894 non-null   float64
 118 sec_app_earliest_cr_line                    71894 non-null   object
 119 sec_app_inq_last_6mths                      71894 non-null   float64
 120 sec_app_mort_acc                            71894 non-null   float64
 121 sec_app_open_acc                            71894 non-null   float64
 122 sec_app_revol_util                          70735 non-null   float64
 123 sec_app_open_act_il                         71894 non-null   float64
 124 sec_app_num_rev_accts                       71894 non-null   float64
 125 sec_app_chargeoff_within_12_mths            71894 non-null   float64
 126 sec_app_collections_12_mths_ex_med          71894 non-null   float64
 127 sec_app_mths_since_last_major_derog         21936 non-null   float64
 128 hardship_flag                               504812 non-null  object
 129 hardship_type                               59934 non-null   object
 130 hardship_reason                             59933 non-null   object
 131 hardship_status                             59934 non-null   object
 132 deferral_term                               59934 non-null   float64
 133 hardship_amount                             73230 non-null   float64
 134 hardship_start_date                         59934 non-null   object
 135 hardship_end_date                           59934 non-null   object
 136 payment_plan_start_date                     59934 non-null   object
 137 hardship_length                             59934 non-null   float64
 138 hardship_dpd                                59934 non-null   float64
 139 hardship_loan_status                        59906 non-null   object
 140 orig_projected_additional_accrued_interest  73229 non-null   float64
 141 hardship_payoff_balance_amount              73230 non-null   float64
 142 hardship_last_payment_amount                73230 non-null   float64
 143 debt_settlement_flag                        518107 non-null  object
 144 debt_settlement_flag_date                   724 non-null     object
 145 settlement_status                           724 non-null     object
 146 settlement_date                             724 non-null     object
 147 settlement_amount                           724 non-null     float64
 148 settlement_percentage                       724 non-null     float64
 149 settlement_term                             724 non-null     float64
dtypes: float64(112), object(38)
memory usage: 596.9+ MB

In [ ]:
#Saving it to .csv
loans.to_csv("loan_database_2019.csv")

In [ ]:
# End of Task1